CREATE TABLE IF NOT EXISTS POSTS (
    NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    VIEWS INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_NO BIGINT NOT NULL,
    TAG_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (POST_NO) REFERENCES POSTS(NO) ON DELETE CASCADE
);
